name = "clfr"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "./dist"

[env.production]
name = "clfr-prod"

[env.staging]
name = "clfr-staging"